# Generated by Django 3.0 on 2022-05-26 12:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='invoiceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('invoiceno', models.CharField(max_length=30)),
                ('date', models.DateField(default=datetime.datetime(2022, 5, 26, 12, 51, 9, 229683, tzinfo=utc), verbose_name='date')),
                ('customerph', models.CharField(max_length=30)),
                ('itendes', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=20)),
                ('prices', models.CharField(max_length=50)),
                ('amount', models.CharField(max_length=50)),
                ('discount', models.CharField(max_length=50)),
                ('total', models.CharField(max_length=500)),
            ],
        ),
    ]
