# Generated by Django 3.0 on 2022-05-27 14:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='serviceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=300)),
                ('phonenumber', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=50)),
                ('numberofpc', models.CharField(max_length=20)),
                ('approvalperson', models.CharField(max_length=20)),
                ('technician', models.CharField(max_length=20)),
                ('servicingdate', models.DateField(default=datetime.datetime(2022, 5, 27, 14, 48, 15, 998411, tzinfo=utc), verbose_name='servicedate')),
                ('remark', models.CharField(max_length=500)),
            ],
        ),
    ]
