# Generated by Django 3.0 on 2022-05-23 14:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=30)),
                ('serialnumber', models.CharField(max_length=30)),
                ('quantity', models.CharField(max_length=20)),
                ('invertorydate', models.DateField(default=datetime.datetime(2022, 5, 23, 14, 13, 36, 139349, tzinfo=utc))),
                ('warrantydate', models.DateField(default=datetime.datetime(2022, 5, 23, 14, 13, 36, 139349, tzinfo=utc))),
                ('expireddate', models.DateField(default=datetime.datetime(2022, 5, 23, 14, 13, 36, 139349, tzinfo=utc))),
                ('amount', models.CharField(max_length=20)),
                ('remark', models.CharField(max_length=50)),
            ],
        ),
    ]
